[package]
name = "turtle"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
bincode = "2.0.1"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
toml = "1.0.3"
tracing-subscriber = "0.3.22"
